openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8899
  description: Generated server url
paths:
  /mobile/search:
    get:
      tags:
      - mobile-controller
      operationId: search
      parameters:
      - name: queryParameters
        in: query
        required: true
        schema:
          type: object
          additionalProperties:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
components:
  schemas:
    Handset:
      type: object
      properties:
        id:
          type: integer
          format: int32
        brand:
          type: string
        phone:
          type: string
        picture:
          type: string
        release:
          $ref: '#/components/schemas/Release'
        sim:
          type: string
        resolution:
          type: string
        hardware:
          $ref: '#/components/schemas/Hardware'
    Hardware:
      type: object
      properties:
        audioJack:
          type: string
        gps:
          type: string
        battery:
          type: string
    Release:
      type: object
      properties:
        announceDate:
          type: string
        priceEur:
          type: number
    SearchResult:
      type: object
      properties:
        total:
          type: integer
          format: int32
        handsets:
          type: array
          items:
            $ref: '#/components/schemas/Handset'
